# baseURL = "http://example.org/"
#baseURL = "http://adsmundodestinos.santiagolab.cl/"
# baseURL = "http://localhost:3000/"
baseURL = "http://adsmundo.cl/ads/"
#baseURL = "http://www.adsmundo.cl/ads/"
languageCode = "en-us"
title = "Ads Mundo Destinos - Internacional"
